set(_CATKIN_CURRENT_PACKAGE "apriltags")
set(apriltags_VERSION "0.0.0")
set(apriltags_MAINTAINER "Bianca Forkel <bianca.forkel@unibw.de>")
set(apriltags_PACKAGE_FORMAT "1")
set(apriltags_BUILD_DEPENDS "eigen" "cmake_modules" "libv4l-dev" "libopencv-dev")
set(apriltags_BUILD_EXPORT_DEPENDS "eigen" "libv4l-dev" "libopencv-dev")
set(apriltags_BUILDTOOL_DEPENDS "catkin")
set(apriltags_BUILDTOOL_EXPORT_DEPENDS )
set(apriltags_EXEC_DEPENDS "eigen" "libv4l-dev" "libopencv-dev")
set(apriltags_RUN_DEPENDS "eigen" "libv4l-dev" "libopencv-dev")
set(apriltags_TEST_DEPENDS )
set(apriltags_DOC_DEPENDS )
set(apriltags_URL_WEBSITE "https://github.com/Humhu/apriltags/")
set(apriltags_URL_BUGTRACKER "")
set(apriltags_URL_REPOSITORY "")
set(apriltags_DEPRECATED "")