set(_CATKIN_CURRENT_PACKAGE "apriltags_msgs")
set(apriltags_msgs_VERSION "0.0.1")
set(apriltags_msgs_MAINTAINER "bifo <bianca.forkel@unibw.de>")
set(apriltags_msgs_PACKAGE_FORMAT "2")
set(apriltags_msgs_BUILD_DEPENDS "std_msgs" "geometry_msgs" "message_generation")
set(apriltags_msgs_BUILD_EXPORT_DEPENDS )
set(apriltags_msgs_BUILDTOOL_DEPENDS "catkin")
set(apriltags_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(apriltags_msgs_EXEC_DEPENDS "message_runtime")
set(apriltags_msgs_RUN_DEPENDS "message_runtime")
set(apriltags_msgs_TEST_DEPENDS )
set(apriltags_msgs_DOC_DEPENDS )
set(apriltags_msgs_URL_WEBSITE "")
set(apriltags_msgs_URL_BUGTRACKER "")
set(apriltags_msgs_URL_REPOSITORY "")
set(apriltags_msgs_DEPRECATED "")