set(_CATKIN_CURRENT_PACKAGE "apriltags_tas")
set(apriltags_tas_VERSION "0.0.0")
set(apriltags_tas_MAINTAINER "Bianca Forkel <bianca.forkel@unibw.de>")
set(apriltags_tas_PACKAGE_FORMAT "2")
set(apriltags_tas_BUILD_DEPENDS "roscpp" "dynamic_reconfigure" "std_msgs" "sensor_msgs" "image_geometry" "image_transport" "tf2_ros" "tf" "cv_bridge" "apriltags" "apriltags_msgs")
set(apriltags_tas_BUILD_EXPORT_DEPENDS "roscpp" "dynamic_reconfigure" "std_msgs" "sensor_msgs" "image_geometry" "image_transport" "tf2_ros" "tf" "cv_bridge" "apriltags" "apriltags_msgs")
set(apriltags_tas_BUILDTOOL_DEPENDS "catkin" "catkin_simple")
set(apriltags_tas_BUILDTOOL_EXPORT_DEPENDS )
set(apriltags_tas_EXEC_DEPENDS "roscpp" "dynamic_reconfigure" "std_msgs" "sensor_msgs" "image_geometry" "image_transport" "tf2_ros" "tf" "cv_bridge" "apriltags" "apriltags_msgs")
set(apriltags_tas_RUN_DEPENDS "roscpp" "dynamic_reconfigure" "std_msgs" "sensor_msgs" "image_geometry" "image_transport" "tf2_ros" "tf" "cv_bridge" "apriltags" "apriltags_msgs")
set(apriltags_tas_TEST_DEPENDS )
set(apriltags_tas_DOC_DEPENDS )
set(apriltags_tas_URL_WEBSITE "")
set(apriltags_tas_URL_BUGTRACKER "")
set(apriltags_tas_URL_REPOSITORY "")
set(apriltags_tas_DEPRECATED "")